# Site settings
title: Justin Howard
email: jmhoward0@gmail.com
description: >
    Software development stories and adventures from
    the front lines of the industry.
baseurl: ""
url: "http://justinhoward.org"
twitter_username: jmhoward0
github_username:  justinhoward
linkedin_username:  jmhoward0
permalink: /:title

# Build settings
markdown: kramdown
