# Site settings
title: Justin Howard
email: jmhoward0@gmail.com
description: >
    Software development stories
baseurl: ""
url: "http://justinhoward.org"
twitter_username: jmhoward0
github_username:  justinhoward
linkedin_username:  jmhoward0
stackoverflow_url: 4231110/justin-howard
stackoverflow_username: Justin Howard
permalink: /:title

# Build settings
markdown: kramdown
